### ISSUE TITLE
suggestion a python library or a protocol sheet

### ISSUE THREAD

**Issue by johnathanhawn** [PyramidTechnologies/Python-RS-232#4]
Im trying to make escrow work in python and need some kind of reference sheet for how i should be talking to an apex 7000 to use in escrow mode.

**Comment by corytodd** [comment]
Hi there, sorry we didn't answer sooner. I'll refer you to our official docs here: https://pyramidacceptors.com/pdf/RS_232.pdf

and the visual diagram here: https://developers.pyramidacceptors.com/coding/2014/08/26/RS-232-Diagram.html
